---
language: go
env:
  - GO111MODULE="on"
go:
  - 1.12
  - 1.13
script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go test -v  -cover -bench .
  - go test -v -covermode=count -coverprofile=coverage.out
after_success:
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
